name: EVE Haul Cleanup

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Run cleanup
        run: |
         curl \
          --verbose \
          --max-time 30 \
          "https://eve-houl.byethost15.com/"
