name: Test Jita Import

on:
  workflow_dispatch:

jobs:
  import-jita:
    runs-on: ubuntu-latest

    steps:
      - name: Test Byet PHP
        run: curl --fail-with-body --show-error --verbose --max-time 60 -A "Mozilla/5.0" "https://eve-houl.byethost15.com/test-github.php"
